package com.example.injusticearchive


data class ChallengeEvent(val character: CharacterCard, val gear: String)


val challengeSchedule = listOf(
    ChallengeEvent(findCharacter("Batman", "Gaslight"),  "Bulletproof Batsuit"),
    ChallengeEvent(findCharacter("Green Lantern", "Red Son"), "Green Power Ring"),
    ChallengeEvent(findCharacter("Superman", "Injustice 2"), "Kryptonian Suit"),
    ChallengeEvent(findCharacter("The Arkham Knight", "Arkham Knight"), "Custom Rifle"),
    ChallengeEvent(findCharacter("Aquaman", null), "Atlantean Polearm"),
    ChallengeEvent( findCharacter("Batman", "Blackest Night"), "Bulletproof Batsuit"),
    ChallengeEvent(findCharacter("Sinestro", "Antimatter"), "Yellow Power Ring"),
    ChallengeEvent(findCharacter("Wonder Woman", "Dawn of Justice"), "Sword & Shield"),
    ChallengeEvent(findCharacter("Scorpion", "Mortal Kombat X"), "Netherrealm Kama"),
    ChallengeEvent(findCharacter("Batgirl", "Arkham Knight"), "Carbonfiber Mask"),
    ChallengeEvent(findCharacter("Zatanna", null), "Arcane Wand"),
    ChallengeEvent(findCharacter("Superman", "New 52"), "Kryptonian Suit"),
    ChallengeEvent(findCharacter("Darkseid", null), "Chestplate"),
    ChallengeEvent(findCharacter("Hawkgirl", "Earth 2"), "Battle Mace"),
    ChallengeEvent(findCharacter("Hal Jordan", "Yellow Lantern"), "Green Power Ring"),
    ChallengeEvent(findCharacter("Martian Manhunter", null), "Martian Garb"),
    ChallengeEvent(findCharacter("Batgirl", null), "Carbonfiber Mask"),
    ChallengeEvent(findCharacter("Superman", "Godfall"), "Kryptonian Suit"),
    ChallengeEvent(findCharacter("Scorpion", "Mortal Kombat"), "Netherrealm Kama"),
    ChallengeEvent(findCharacter("Hawkgirl", "Regime"), "Battle Mace"),
    ChallengeEvent(findCharacter("Aquaman", "Injustice 2"), "Atlantean Polearm"),
    ChallengeEvent(findCharacter("Bane", "Luchador"), "Venom Harness"),
    ChallengeEvent(findCharacter("Hal Jordan", "Red Lantern"), "Green Power Ring"),
    ChallengeEvent(findCharacter("Lord Joker", "Batman Ninja"), "Pistol"),
    ChallengeEvent(findCharacter("Lobo", "Bounty Hunter"), "Hook"),
    ChallengeEvent(findCharacter("Killer Croc", "Arkham"), "Sharpened Teeth"),
    ChallengeEvent(findCharacter("Killer Frost", null), "Icebound Necklace"),
    ChallengeEvent(findCharacter("Black Adam", "Kahndaq"), "Kahndaq Garb"),
    ChallengeEvent(findCharacter("Deadshot", "Suicide Squad"), "Balaclava"),
    ChallengeEvent(findCharacter("Jessica Cruz", "Rebirth"), "Green Power Ring"),
    ChallengeEvent(findCharacter("Harley Quinn", "Suicide Squad"), ".357 Revolver"),
    ChallengeEvent(findCharacter("Superman", "Dawn of Justice"), "Kryptonian Suit"),
    ChallengeEvent(findCharacter("Batman Beyond", "Animated"), "Bulletproof Batsuit"),
    ChallengeEvent(findCharacter("Raven", null), "Azarthian Cloak"),
    ChallengeEvent(findCharacter("Solomon Grundy", "Earth 2"), "Butcher's Knife"),
    ChallengeEvent(findCharacter("Static", null), "Charged Disc"),
    ChallengeEvent(findCharacter("Batman", "Flashpoint"), "Bulletproof Batsuit"),
    ChallengeEvent(findCharacter("Green Lantern", "John Stewart"), "Green Power Ring"),
    ChallengeEvent(findCharacter("The Flash", "Earth 2"), "Hyperspeed Suit"),
    ChallengeEvent(findCharacter("Darkseid", "Apokolips"), "Chestplate"),
    ChallengeEvent(findCharacter("Catwoman", "Arkham Knight"), "Steel Claws"),
    ChallengeEvent(findCharacter("Martian Manhunter", "Blackest Night"), "Martian Garb"),
    ChallengeEvent(findCharacter("The Joker", "Arkham Origins"), "Pistol"),
    ChallengeEvent(findCharacter("Green Arrow", "Rebirth"), "Longbow"),
    ChallengeEvent(findCharacter("Raven", "Teen Titans"), "Azarthian Cloak"),
    ChallengeEvent(findCharacter("Wonder Woman", "New 52"), "Sword & Shield"),
    ChallengeEvent(findCharacter("The Joker", "Suicide Squad"), "Pistol"),
    ChallengeEvent(findCharacter("Catwoman", "Ame-Comi"), "Diamond Claws"),
    ChallengeEvent(findCharacter("Harley Quinn", "Arkham Knight"), ".357 Revolver"),
    ChallengeEvent(findCharacter("Bane", "Arkham Origins"), "Venom Harness"),
    ChallengeEvent(findCharacter("Batman", "Batman Ninja"), "Bulletproof Batsuit"),
    ChallengeEvent(findCharacter("Raven", "Rebirth"), "Azarthian Cloak"),
    ChallengeEvent(findCharacter("Scorpion", "Klassic"), "Kama ")
)
